/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetActivateRequest {
    tokenWithUserid?: string;
    tokenWithoutUserid?: string;
}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI {

    /**
     * メールアドレスの有効化
     * getActivateEmailAddress
     */
    async getActivateRaw(requestParameters: GetActivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['tokenWithUserid'] != null) {
            queryParameters['token-with-userid'] = requestParameters['tokenWithUserid'];
        }

        if (requestParameters['tokenWithoutUserid'] != null) {
            queryParameters['token-without-userid'] = requestParameters['tokenWithoutUserid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/activate`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * メールアドレスの有効化
     * getActivateEmailAddress
     */
    async getActivate(requestParameters: GetActivateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getActivateRaw(requestParameters, initOverrides);
    }

}
