version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      types:
        patterns:
          - '@types/*'
      lint-formatter:
        patterns:
          - '*eslint*'
          - '*prettier*'
      patches:
        update-types:
          - 'patch'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      actions-deps:
        patterns:
          - '*'
