/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 解説の詳細
 * @export
 * @interface Editorial
 */
export interface Editorial {
    /**
     * 解説ID
     * @type {number}
     * @memberof Editorial
     */
    id: number;
    /**
     * 作成日時
     * @type {Date}
     * @memberof Editorial
     */
    createdAt: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof Editorial
     */
    updatedAt?: Date;
    /**
     * 投稿者のユーザーID
     * @type {number}
     * @memberof Editorial
     */
    authorId: number;
    /**
     * 解説本文 (HTML)
     * @type {string}
     * @memberof Editorial
     */
    statement: string;
    /**
     * 解説が全体公開かどうか.
     * 
     * * `true` - 公開
     * * `false` - 非公開 (問題の作者のみ閲覧可)
     * @type {boolean}
     * @memberof Editorial
     */
    isPublic: boolean;
}

/**
 * Check if a given object implements the Editorial interface.
 */
export function instanceOfEditorial(value: object): value is Editorial {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('statement' in value) || value['statement'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    return true;
}

export function EditorialFromJSON(json: any): Editorial {
    return EditorialFromJSONTyped(json, false);
}

export function EditorialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Editorial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'authorId': json['authorId'],
        'statement': json['statement'],
        'isPublic': json['isPublic'],
    };
}

  export function EditorialToJSON(json: any): Editorial {
      return EditorialToJSONTyped(json, false);
  }

  export function EditorialToJSONTyped(value?: Editorial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'authorId': value['authorId'],
        'statement': value['statement'],
        'isPublic': value['isPublic'],
    };
}

