/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGoogleAuthParams500Response
 */
export interface GetGoogleAuthParams500Response {
    /**
     * 
     * @type {string}
     * @memberof GetGoogleAuthParams500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetGoogleAuthParams500Response interface.
 */
export function instanceOfGetGoogleAuthParams500Response(value: object): value is GetGoogleAuthParams500Response {
    return true;
}

export function GetGoogleAuthParams500ResponseFromJSON(json: any): GetGoogleAuthParams500Response {
    return GetGoogleAuthParams500ResponseFromJSONTyped(json, false);
}

export function GetGoogleAuthParams500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGoogleAuthParams500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

  export function GetGoogleAuthParams500ResponseToJSON(json: any): GetGoogleAuthParams500Response {
      return GetGoogleAuthParams500ResponseToJSONTyped(json, false);
  }

  export function GetGoogleAuthParams500ResponseToJSONTyped(value?: GetGoogleAuthParams500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

