/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGoogleAuthParams200Response
 */
export interface GetGoogleAuthParams200Response {
    /**
     * 
     * @type {string}
     * @memberof GetGoogleAuthParams200Response
     */
    url: string;
}

/**
 * Check if a given object implements the GetGoogleAuthParams200Response interface.
 */
export function instanceOfGetGoogleAuthParams200Response(value: object): value is GetGoogleAuthParams200Response {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GetGoogleAuthParams200ResponseFromJSON(json: any): GetGoogleAuthParams200Response {
    return GetGoogleAuthParams200ResponseFromJSONTyped(json, false);
}

export function GetGoogleAuthParams200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGoogleAuthParams200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

  export function GetGoogleAuthParams200ResponseToJSON(json: any): GetGoogleAuthParams200Response {
      return GetGoogleAuthParams200ResponseToJSONTyped(json, false);
  }

  export function GetGoogleAuthParams200ResponseToJSONTyped(value?: GetGoogleAuthParams200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

