/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ジャッジの状態
 * 
 * * `AC` - 正解
 * * `WA` - 不正解
 * * `CE` - コンパイルエラー
 * * `IE` - 内部エラー
 * * `MLE` - メモリ制限超過
 * * `RE` - 実行時エラー
 * * `TLE` - 実行時間超過
 * * `WJ` - ジャッジ待ち
 * @export
 */
export const JudgeStatus = {
    Ac: 'AC',
    Wa: 'WA',
    Ce: 'CE',
    Ie: 'IE',
    Mle: 'MLE',
    Re: 'RE',
    Tle: 'TLE',
    Wj: 'WJ'
} as const;
export type JudgeStatus = typeof JudgeStatus[keyof typeof JudgeStatus];


export function instanceOfJudgeStatus(value: any): boolean {
    for (const key in JudgeStatus) {
        if (Object.prototype.hasOwnProperty.call(JudgeStatus, key)) {
            if (JudgeStatus[key as keyof typeof JudgeStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JudgeStatusFromJSON(json: any): JudgeStatus {
    return JudgeStatusFromJSONTyped(json, false);
}

export function JudgeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JudgeStatus {
    return json as JudgeStatus;
}

export function JudgeStatusToJSON(value?: JudgeStatus | null): any {
    return value as any;
}

export function JudgeStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JudgeStatus {
    return value as JudgeStatus;
}

