/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTestcaseRequestInner
 */
export interface PostTestcaseRequestInner {
    /**
     * 
     * @type {string}
     * @memberof PostTestcaseRequestInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PostTestcaseRequestInner
     */
    testInput: string;
    /**
     * 
     * @type {string}
     * @memberof PostTestcaseRequestInner
     */
    testOutput: string;
}

/**
 * Check if a given object implements the PostTestcaseRequestInner interface.
 */
export function instanceOfPostTestcaseRequestInner(value: object): value is PostTestcaseRequestInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('testInput' in value) || value['testInput'] === undefined) return false;
    if (!('testOutput' in value) || value['testOutput'] === undefined) return false;
    return true;
}

export function PostTestcaseRequestInnerFromJSON(json: any): PostTestcaseRequestInner {
    return PostTestcaseRequestInnerFromJSONTyped(json, false);
}

export function PostTestcaseRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTestcaseRequestInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'testInput': json['testInput'],
        'testOutput': json['testOutput'],
    };
}

  export function PostTestcaseRequestInnerToJSON(json: any): PostTestcaseRequestInner {
      return PostTestcaseRequestInnerToJSONTyped(json, false);
  }

  export function PostTestcaseRequestInnerToJSONTyped(value?: PostTestcaseRequestInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'testInput': value['testInput'],
        'testOutput': value['testOutput'],
    };
}

