/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 回答の提出リクエスト
 * @export
 * @interface PostSubmissionRequest
 */
export interface PostSubmissionRequest {
    /**
     * 提出コードの言語ID
     * @type {number}
     * @memberof PostSubmissionRequest
     */
    languageId?: number;
    /**
     * ソースコード
     * @type {string}
     * @memberof PostSubmissionRequest
     */
    source?: string;
}

/**
 * Check if a given object implements the PostSubmissionRequest interface.
 */
export function instanceOfPostSubmissionRequest(value: object): value is PostSubmissionRequest {
    return true;
}

export function PostSubmissionRequestFromJSON(json: any): PostSubmissionRequest {
    return PostSubmissionRequestFromJSONTyped(json, false);
}

export function PostSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'languageId': json['languageId'] == null ? undefined : json['languageId'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

  export function PostSubmissionRequestToJSON(json: any): PostSubmissionRequest {
      return PostSubmissionRequestToJSONTyped(json, false);
  }

  export function PostSubmissionRequestToJSONTyped(value?: PostSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'languageId': value['languageId'],
        'source': value['source'],
    };
}

