/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 問題の投稿リクエスト
 * @export
 * @interface PostProblemRequest
 */
export interface PostProblemRequest {
    /**
     * 問題タイトル
     * @type {string}
     * @memberof PostProblemRequest
     */
    title: string;
    /**
     * 難易度
     * @type {number}
     * @memberof PostProblemRequest
     */
    difficulty: number;
    /**
     * 問題文 (HTML形式)
     * @type {string}
     * @memberof PostProblemRequest
     */
    statement: string;
    /**
     * 実行時間制限 (ms)
     * @type {number}
     * @memberof PostProblemRequest
     */
    timeLimit: number;
    /**
     * メモリ制限 (MiB)
     * @type {number}
     * @memberof PostProblemRequest
     */
    memoryLimit: number;
}

/**
 * Check if a given object implements the PostProblemRequest interface.
 */
export function instanceOfPostProblemRequest(value: object): value is PostProblemRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('statement' in value) || value['statement'] === undefined) return false;
    if (!('timeLimit' in value) || value['timeLimit'] === undefined) return false;
    if (!('memoryLimit' in value) || value['memoryLimit'] === undefined) return false;
    return true;
}

export function PostProblemRequestFromJSON(json: any): PostProblemRequest {
    return PostProblemRequestFromJSONTyped(json, false);
}

export function PostProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProblemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'difficulty': json['difficulty'],
        'statement': json['statement'],
        'timeLimit': json['timeLimit'],
        'memoryLimit': json['memoryLimit'],
    };
}

  export function PostProblemRequestToJSON(json: any): PostProblemRequest {
      return PostProblemRequestToJSONTyped(json, false);
  }

  export function PostProblemRequestToJSONTyped(value?: PostProblemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'difficulty': value['difficulty'],
        'statement': value['statement'],
        'timeLimit': value['timeLimit'],
        'memoryLimit': value['memoryLimit'],
    };
}

