/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 問題の要約
 * @export
 * @interface ProblemSummary
 */
export interface ProblemSummary {
    /**
     * 問題ID
     * @type {string}
     * @memberof ProblemSummary
     */
    id: string;
    /**
     * 問題タイトル
     * @type {string}
     * @memberof ProblemSummary
     */
    title: string;
    /**
     * 作問者のユーザーID
     * @type {number}
     * @memberof ProblemSummary
     */
    authorId: number;
    /**
     * 問題が全体公開かどうか.
     * 
     * * `true` - 公開
     * * `false` - 非公開 (問題の作者のみ閲覧可)
     * @type {boolean}
     * @memberof ProblemSummary
     */
    isPublic: boolean;
    /**
     * 難易度
     * @type {number}
     * @memberof ProblemSummary
     */
    difficulty: number;
    /**
     * 実行時間制限 (ms)
     * @type {number}
     * @memberof ProblemSummary
     */
    timeLimit: number;
    /**
     * メモリ制限 (MiB)
     * @type {number}
     * @memberof ProblemSummary
     */
    memoryLimit: number;
    /**
     * 
     * @type {number}
     * @memberof ProblemSummary
     */
    solvedCount: number;
    /**
     * 
     * @type {Date}
     * @memberof ProblemSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProblemSummary
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ProblemSummary interface.
 */
export function instanceOfProblemSummary(value: object): value is ProblemSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('timeLimit' in value) || value['timeLimit'] === undefined) return false;
    if (!('memoryLimit' in value) || value['memoryLimit'] === undefined) return false;
    if (!('solvedCount' in value) || value['solvedCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProblemSummaryFromJSON(json: any): ProblemSummary {
    return ProblemSummaryFromJSONTyped(json, false);
}

export function ProblemSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'authorId': json['authorId'],
        'isPublic': json['isPublic'],
        'difficulty': json['difficulty'],
        'timeLimit': json['timeLimit'],
        'memoryLimit': json['memoryLimit'],
        'solvedCount': json['solvedCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function ProblemSummaryToJSON(json: any): ProblemSummary {
      return ProblemSummaryToJSONTyped(json, false);
  }

  export function ProblemSummaryToJSONTyped(value?: ProblemSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'authorId': value['authorId'],
        'isPublic': value['isPublic'],
        'difficulty': value['difficulty'],
        'timeLimit': value['timeLimit'],
        'memoryLimit': value['memoryLimit'],
        'solvedCount': value['solvedCount'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

