/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 解説の変更リクエスト.
 * @export
 * @interface PutEditorialRequest
 */
export interface PutEditorialRequest {
    /**
     * 解説本文 (HTML)
     * @type {string}
     * @memberof PutEditorialRequest
     */
    statement?: string;
    /**
     * 公開されているかどうか
     * @type {boolean}
     * @memberof PutEditorialRequest
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the PutEditorialRequest interface.
 */
export function instanceOfPutEditorialRequest(value: object): value is PutEditorialRequest {
    return true;
}

export function PutEditorialRequestFromJSON(json: any): PutEditorialRequest {
    return PutEditorialRequestFromJSONTyped(json, false);
}

export function PutEditorialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutEditorialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'statement': json['statement'] == null ? undefined : json['statement'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

  export function PutEditorialRequestToJSON(json: any): PutEditorialRequest {
      return PutEditorialRequestToJSONTyped(json, false);
  }

  export function PutEditorialRequestToJSONTyped(value?: PutEditorialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statement': value['statement'],
        'isPublic': value['isPublic'],
    };
}

