/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutMeRequest
 */
export interface PutMeRequest {
    /**
     * 
     * @type {string}
     * @memberof PutMeRequest
     */
    userName?: string;
    /**
     * 
     * @type {Blob}
     * @memberof PutMeRequest
     */
    icon?: Blob;
    /**
     * 
     * @type {string}
     * @memberof PutMeRequest
     */
    xLink?: string;
    /**
     * 
     * @type {string}
     * @memberof PutMeRequest
     */
    githubLink?: string;
    /**
     * 
     * @type {string}
     * @memberof PutMeRequest
     */
    selfIntroduction?: string;
}

/**
 * Check if a given object implements the PutMeRequest interface.
 */
export function instanceOfPutMeRequest(value: object): value is PutMeRequest {
    return true;
}

export function PutMeRequestFromJSON(json: any): PutMeRequest {
    return PutMeRequestFromJSONTyped(json, false);
}

export function PutMeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutMeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'xLink': json['xLink'] == null ? undefined : json['xLink'],
        'githubLink': json['githubLink'] == null ? undefined : json['githubLink'],
        'selfIntroduction': json['selfIntroduction'] == null ? undefined : json['selfIntroduction'],
    };
}

  export function PutMeRequestToJSON(json: any): PutMeRequest {
      return PutMeRequestToJSONTyped(json, false);
  }

  export function PutMeRequestToJSONTyped(value?: PutMeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'icon': value['icon'],
        'xLink': value['xLink'],
        'githubLink': value['githubLink'],
        'selfIntroduction': value['selfIntroduction'],
    };
}

