/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 問題の変更リクエスト
 * @export
 * @interface PutProblemRequest
 */
export interface PutProblemRequest {
    /**
     * 問題タイトル
     * @type {string}
     * @memberof PutProblemRequest
     */
    title: string;
    /**
     * 問題が全体公開かどうか.
     * 
     * * `true` - 公開
     * * `false` - 非公開 (問題の作者のみ閲覧可)
     * @type {boolean}
     * @memberof PutProblemRequest
     */
    isPublic: boolean;
    /**
     * 難易度
     * @type {number}
     * @memberof PutProblemRequest
     */
    difficulty: number;
    /**
     * 問題文 (HTML形式)
     * @type {string}
     * @memberof PutProblemRequest
     */
    statement?: string;
    /**
     * 実行時間制限 (ms)
     * @type {number}
     * @memberof PutProblemRequest
     */
    timeLimit: number;
    /**
     * メモリ制限 (MiB)
     * @type {number}
     * @memberof PutProblemRequest
     */
    memoryLimit: number;
}

/**
 * Check if a given object implements the PutProblemRequest interface.
 */
export function instanceOfPutProblemRequest(value: object): value is PutProblemRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('timeLimit' in value) || value['timeLimit'] === undefined) return false;
    if (!('memoryLimit' in value) || value['memoryLimit'] === undefined) return false;
    return true;
}

export function PutProblemRequestFromJSON(json: any): PutProblemRequest {
    return PutProblemRequestFromJSONTyped(json, false);
}

export function PutProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutProblemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'isPublic': json['isPublic'],
        'difficulty': json['difficulty'],
        'statement': json['statement'] == null ? undefined : json['statement'],
        'timeLimit': json['timeLimit'],
        'memoryLimit': json['memoryLimit'],
    };
}

  export function PutProblemRequestToJSON(json: any): PutProblemRequest {
      return PutProblemRequestToJSONTyped(json, false);
  }

  export function PutProblemRequestToJSONTyped(value?: PutProblemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'isPublic': value['isPublic'],
        'difficulty': value['difficulty'],
        'statement': value['statement'],
        'timeLimit': value['timeLimit'],
        'memoryLimit': value['memoryLimit'],
    };
}

