/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ログイン後のパスワード変更用
 * @export
 * @interface PutPasswordRequest
 */
export interface PutPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PutPasswordRequest
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PutPasswordRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PutPasswordRequest interface.
 */
export function instanceOfPutPasswordRequest(value: object): value is PutPasswordRequest {
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PutPasswordRequestFromJSON(json: any): PutPasswordRequest {
    return PutPasswordRequestFromJSONTyped(json, false);
}

export function PutPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
    };
}

  export function PutPasswordRequestToJSON(json: any): PutPasswordRequest {
      return PutPasswordRequestToJSONTyped(json, false);
  }

  export function PutPasswordRequestToJSONTyped(value?: PutPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
    };
}

