/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 単体のテストケースの編集
 * @export
 * @interface PutTestcaseRequest
 */
export interface PutTestcaseRequest {
    /**
     * 
     * @type {string}
     * @memberof PutTestcaseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PutTestcaseRequest
     */
    testInput: string;
    /**
     * 
     * @type {string}
     * @memberof PutTestcaseRequest
     */
    testOutput: string;
}

/**
 * Check if a given object implements the PutTestcaseRequest interface.
 */
export function instanceOfPutTestcaseRequest(value: object): value is PutTestcaseRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('testInput' in value) || value['testInput'] === undefined) return false;
    if (!('testOutput' in value) || value['testOutput'] === undefined) return false;
    return true;
}

export function PutTestcaseRequestFromJSON(json: any): PutTestcaseRequest {
    return PutTestcaseRequestFromJSONTyped(json, false);
}

export function PutTestcaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutTestcaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'testInput': json['testInput'],
        'testOutput': json['testOutput'],
    };
}

  export function PutTestcaseRequestToJSON(json: any): PutTestcaseRequest {
      return PutTestcaseRequestToJSONTyped(json, false);
  }

  export function PutTestcaseRequestToJSONTyped(value?: PutTestcaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'testInput': value['testInput'],
        'testOutput': value['testOutput'],
    };
}

