/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeTraqAuthRequest
 */
export interface RevokeTraqAuthRequest {
    /**
     * The access token to revoke
     * @type {string}
     * @memberof RevokeTraqAuthRequest
     */
    token: string;
}

/**
 * Check if a given object implements the RevokeTraqAuthRequest interface.
 */
export function instanceOfRevokeTraqAuthRequest(value: object): value is RevokeTraqAuthRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function RevokeTraqAuthRequestFromJSON(json: any): RevokeTraqAuthRequest {
    return RevokeTraqAuthRequestFromJSONTyped(json, false);
}

export function RevokeTraqAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeTraqAuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

  export function RevokeTraqAuthRequestToJSON(json: any): RevokeTraqAuthRequest {
      return RevokeTraqAuthRequestToJSONTyped(json, false);
  }

  export function RevokeTraqAuthRequestToJSONTyped(value?: RevokeTraqAuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

