/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * email+password登録
 * @export
 * @interface Signup
 */
export interface Signup {
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    token: string;
}

/**
 * Check if a given object implements the Signup interface.
 */
export function instanceOfSignup(value: object): value is Signup {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function SignupFromJSON(json: any): Signup {
    return SignupFromJSONTyped(json, false);
}

export function SignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Signup {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'password': json['password'],
        'token': json['token'],
    };
}

  export function SignupToJSON(json: any): Signup {
      return SignupToJSONTyped(json, false);
  }

  export function SignupToJSONTyped(value?: Signup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'password': value['password'],
        'token': value['token'],
    };
}

