/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * テストケース
 * @export
 * @interface Testcase
 */
export interface Testcase {
    /**
     * 
     * @type {string}
     * @memberof Testcase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Testcase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Testcase
     */
    testInput: string;
    /**
     * 
     * @type {string}
     * @memberof Testcase
     */
    testOutput: string;
    /**
     * 
     * @type {Date}
     * @memberof Testcase
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Testcase
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Testcase interface.
 */
export function instanceOfTestcase(value: object): value is Testcase {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('testInput' in value) || value['testInput'] === undefined) return false;
    if (!('testOutput' in value) || value['testOutput'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TestcaseFromJSON(json: any): Testcase {
    return TestcaseFromJSONTyped(json, false);
}

export function TestcaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Testcase {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'testInput': json['testInput'],
        'testOutput': json['testOutput'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function TestcaseToJSON(json: any): Testcase {
      return TestcaseToJSONTyped(json, false);
  }

  export function TestcaseToJSONTyped(value?: Testcase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'testInput': value['testInput'],
        'testOutput': value['testOutput'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

