/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestcaseSummary
 */
export interface TestcaseSummary {
    /**
     * 
     * @type {string}
     * @memberof TestcaseSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TestcaseSummary
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof TestcaseSummary
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TestcaseSummary
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TestcaseSummary interface.
 */
export function instanceOfTestcaseSummary(value: object): value is TestcaseSummary {
    return true;
}

export function TestcaseSummaryFromJSON(json: any): TestcaseSummary {
    return TestcaseSummaryFromJSONTyped(json, false);
}

export function TestcaseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestcaseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

  export function TestcaseSummaryToJSON(json: any): TestcaseSummary {
      return TestcaseSummaryToJSONTyped(json, false);
  }

  export function TestcaseSummaryToJSONTyped(value?: TestcaseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

