/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestcaseSummary } from './TestcaseSummary';
import {
    TestcaseSummaryFromJSON,
    TestcaseSummaryFromJSONTyped,
    TestcaseSummaryToJSON,
    TestcaseSummaryToJSONTyped,
} from './TestcaseSummary';

/**
 * 
 * @export
 * @interface TestcaseSummaries
 */
export interface TestcaseSummaries {
    /**
     * 
     * @type {Array<TestcaseSummary>}
     * @memberof TestcaseSummaries
     */
    testcaseSummaries?: Array<TestcaseSummary>;
}

/**
 * Check if a given object implements the TestcaseSummaries interface.
 */
export function instanceOfTestcaseSummaries(value: object): value is TestcaseSummaries {
    return true;
}

export function TestcaseSummariesFromJSON(json: any): TestcaseSummaries {
    return TestcaseSummariesFromJSONTyped(json, false);
}

export function TestcaseSummariesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestcaseSummaries {
    if (json == null) {
        return json;
    }
    return {
        
        'testcaseSummaries': json['testcaseSummaries'] == null ? undefined : ((json['testcaseSummaries'] as Array<any>).map(TestcaseSummaryFromJSON)),
    };
}

  export function TestcaseSummariesToJSON(json: any): TestcaseSummaries {
      return TestcaseSummariesToJSONTyped(json, false);
  }

  export function TestcaseSummariesToJSONTyped(value?: TestcaseSummaries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'testcaseSummaries': value['testcaseSummaries'] == null ? undefined : ((value['testcaseSummaries'] as Array<any>).map(TestcaseSummaryToJSON)),
    };
}

