/* tslint:disable */
/* eslint-disable */
/**
 * traO Judge API
 * traO Judge API (front ↔ back)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * login
 * @export
 * @interface UserEmailAndPassword
 */
export interface UserEmailAndPassword {
    /**
     * 
     * @type {string}
     * @memberof UserEmailAndPassword
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserEmailAndPassword
     */
    password: string;
}

/**
 * Check if a given object implements the UserEmailAndPassword interface.
 */
export function instanceOfUserEmailAndPassword(value: object): value is UserEmailAndPassword {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserEmailAndPasswordFromJSON(json: any): UserEmailAndPassword {
    return UserEmailAndPasswordFromJSONTyped(json, false);
}

export function UserEmailAndPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEmailAndPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

  export function UserEmailAndPasswordToJSON(json: any): UserEmailAndPassword {
      return UserEmailAndPasswordToJSONTyped(json, false);
  }

  export function UserEmailAndPasswordToJSONTyped(value?: UserEmailAndPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

